---
version: "3.7"
services:
  db:
    container_name: itil_db
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "159753"
      MYSQL_DATABASE: itil
      command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  api:
    container_name: test_api
    environment:
      - EnvDBtype="sqlite"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - .:/app/
networks:
  default:
volumes:
  mysql_data: